sever:
  port: 8080
  context-path: /


spring:
  datasource:
    name: blog #数据库名
    url: jdbc:mysql://localhost:3306/blog #url
    username: root  #用户名
    password: shw19950815  #密码
    driver-class-name: com.mysql.cj.jdbc.Driver  #数据root库链接驱动


mybatis:
  mapper-locations: classpath:mapper/*.xml  #配置映射文件
  type-aliases-package: com.example.blog.bean #配置实体类